name: CI
on: [push]
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Log some stuff
        run: |
          printenv
          git log
        
      - name: Hang for a minute
        run: sleep 10
